{% set name = "schemaorg" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36ff16341c447b1da6f58287478a4eb8cf8f3d21f4ab961474c8821181629a08

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - python >=3
    - pyaml
    - lxml

test:
  imports:
    - schemaorg
    - schemaorg.version
    - schemaorg.utils
    - schemaorg.defaults
    - schemaorg.data
    - schemaorg.logger
    - schemaorg.main
    - schemaorg.main.parse
    - schemaorg.main.parse.base
    - schemaorg.main.parse.validate
    - schemaorg.main.parse.recipe
    - schemaorg.templates
    - schemaorg.templates.google
    - schemaorg.templates.metadata


about:
  home: https://github.com/openschemas/schemaorg
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: Python functions for applied use of schema.org
  description: Python functions for instantiating and validating schemas.
  doc_url: https://openschemas.github.io/schemaorg
  dev_url: https://github.com/openschemas/schemaorg

extra:
  recipe-maintainers:
    - vsoch
